[plugins]
spring-boot = { id = "org.springframework.boot", version = "3.3.1" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.0" }

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }

apache-httpclient = { module = "org.apache.httpcomponents:httpclient", version = "4.5.13" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "20.1.0" }

# testing
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test"}
wiremock = { module = "com.github.tomakehurst:wiremock-jre8-standalone", version = "2.35.0" }
assertj = { module = "org.assertj:assertj-core", version = "3.23.1"}
jsonassert = { module = "org.skyscreamer:jsonassert", version = "1.5.0"}
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version = "1.3.2"}
